### ISSUE TITLE
responseName.Sample always returns 0

### ISSUE THREAD

**Issue by markus-perl** [microknights/Gender-API#1]
Hey Frank,

Hope you are well. 

I'm currently in contact with a customer who is using your C# implementation and we think there might be something wrong with the number of samples variable.

```
const string Name = "Frank Nielsen";
                var responseName = await client.GetByNameAndCountry2Alpha(Name, "DK");
                if( responseName.IsSuccess ) {
                    Console.WriteLine($"{Name} is {responseName.GenderType.DisplayName}. Samples: {responseName.Sample}");
                }
                else {
                    Console.WriteLine($"ERRORS: {responseName.ErrorCode}-{responseName.Exception.Message}");
                }
```

If we run this example {responseName.Sample} will always return 0. I think this happens because the variable in the JSON response is called "sample**s**" and not "sample". Could you take a look at this?

Best regards,
Markus

**Comment by microknights** [comment]
The issue is correct, and i have fixed it. A new NuGet package v1.3.1 is uploaded, and available shortly.

The property `Sample` is now obsoleted and should be replaced by `Samples`. Both `Sample` and `Samples` now return correct value.

**Comment by markus-perl** [comment]
Wow, thank you for this quick response. I will test it as soon as the package is available. Best, Markus

**Comment by microknights** [comment]
@markus-perl did you have the time to test the fix?

**Comment by markus-perl** [comment]
Oh, yes, everything works as expected. Thanks again for the quick fix :-)
